name: spotify_album_finder

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    # bootstrap実行後に実行したいコマンドを定義
    # hooks:
    # post: melos exec -exists="l10n.yaml" fvm dart format lib/10n

    dependencies:
      go_router: ^14.8.1

    dev_dependencies:
      very_good_analysis: ^7.0.0